// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh9A7f4ryi3EWuT35INNSsVQkWywEJO0Y',
    appId: '1:612714814713:web:4ad4c99601ad62230ad628',
    messagingSenderId: '612714814713',
    projectId: 'konversi-suhu-9dbdf',
    authDomain: 'konversi-suhu-9dbdf.firebaseapp.com',
    storageBucket: 'konversi-suhu-9dbdf.firebasestorage.app',
    measurementId: 'G-JRE7MSWTX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZjdxHX20ECpNUDE_QvtEIWrNdkCjV-Go',
    appId: '1:612714814713:android:6248b21395a1c47e0ad628',
    messagingSenderId: '612714814713',
    projectId: 'konversi-suhu-9dbdf',
    storageBucket: 'konversi-suhu-9dbdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuigfoNbq3YVzBLsFqiBxx5jFhmbJxuP8',
    appId: '1:612714814713:ios:d9e2ccd999e2a3eb0ad628',
    messagingSenderId: '612714814713',
    projectId: 'konversi-suhu-9dbdf',
    storageBucket: 'konversi-suhu-9dbdf.firebasestorage.app',
    iosBundleId: 'com.example.learn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuigfoNbq3YVzBLsFqiBxx5jFhmbJxuP8',
    appId: '1:612714814713:ios:d9e2ccd999e2a3eb0ad628',
    messagingSenderId: '612714814713',
    projectId: 'konversi-suhu-9dbdf',
    storageBucket: 'konversi-suhu-9dbdf.firebasestorage.app',
    iosBundleId: 'com.example.learn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh9A7f4ryi3EWuT35INNSsVQkWywEJO0Y',
    appId: '1:612714814713:web:89c771b7d15faf180ad628',
    messagingSenderId: '612714814713',
    projectId: 'konversi-suhu-9dbdf',
    authDomain: 'konversi-suhu-9dbdf.firebaseapp.com',
    storageBucket: 'konversi-suhu-9dbdf.firebasestorage.app',
    measurementId: 'G-8DB33NWZY8',
  );
}
